### ISSUE TITLE
docs.rs seems to be down

### ISSUE THREAD

**Issue by phil-opp** [rust-lang-nursery/docs.rs#246]
https://docs.rs/ does not load for me. https://downforeveryoneorjustme.com/docs.rs reports the same.

**Comment by joepie91** [comment]
The issue seems to be localized; I've seen a number of reports on IRC as well, but it has worked fine for me the entire time (even while downforeveryoneorjustme said it was down), and also for some others.

**Comment by j-channings** [comment]
Same for me, from my office network. Loads OK via my mobile network.

```
Non-authoritative answer:
Name:   docs.rs
Address: 95.211.95.204
Name:   docs.rs
Address: 2001:1af8:4020:a00f:10::1
```
95.211.95.204 is not routable from my mobile or my office PC.

```

2001:1af8:4020:a00f:10::1 is not reachable from my office PC - probably because IPv6 is misconfigured here.

**Comment by joepie91** [comment]
Seems IPv4 is blackholed, but IPv6 is not. IPv4 isn't reachable for me either, but IPv6 works fine.

**Comment by mcandre** [comment]
Possibly related: GitHub continues to present random cache values as it did last night during the database migration. When I reload this #246 issue page in a new browser tab, I get often different comments and like counts.

**Comment by lorenz** [comment]
I set up https://docsrs.brun.one/ as a temporary proxy while it's down

**Comment by pietroalbini** [comment]
> Possibly related?
>
> GitHub continues to present random cache values, as it did last night during the database migration. When I reload this #246 issue page in a new browser tab, I get often different comments and like counts.

This is not related to the GitHub outage. There has been a problem with the hosting provider, and the rustdoc team is in contact with them to fix it.

**Comment by QuietMisdreavus** [comment]
Correct, the site is back up.

Here is the statuspage announcement for this incident: http://status.crates.io/incidents/jsvsy32z0p6r

We're going to post a retrospective about this later this week, but for now, i'm closing this issue.

**Comment by sameer** [comment]
Just curious, what was the DMCA takedown request was in relation to?

**Comment by steveklabnik** [comment]
@sameer we'll eventually be answering as much as we can in the retrospective, but until then, we can't talk about it. thanks!

**Comment by KNWR** [comment]
Docs.rs is still not working for me :(
