### ISSUE TITLE
Rustdoc-args field is no longer applied when building build.rs

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/docs.rs#262]
The proc-macro2 crate uses the following in Cargo.toml:

```toml
[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "procmacro2_semver_exempt"]
```

Then we read the cfg from build.rs:

```rust
if cfg!(procmacro2_semver_exempt) {
    /* ... */
}
```

In the past the `rustdoc-args` has always been applied when compiling build.rs. Recently (within the past month) our documentation build in docs.rs began failing because build.rs is no longer seeing the cfg set by `rustdoc-args`. https://github.com/rust-lang-nursery/docs.rs/compare/32102ce458b34f750ef190182116d9583491a64b...c695234cdf5b63f9727063e54edb5d980b535135. Is it possible that this is a regression introduced by docs.rs? Or is it a rustc or rustdoc bug?

Locally running `RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo doc` does work.

See https://github.com/alexcrichton/proc-macro2/issues/145 for details.

**Comment by QuietMisdreavus** [comment]
`rustdoc-args` is not the same as `RUSTFLAGS`. It's instead like `RUSTDOCFLAGS` - the former is given to rustc, the latter to rustdoc. Going from [the logs i referenced in the linked issue](https://github.com/alexcrichton/proc-macro2/issues/145#issuecomment-437698794), it looks like `rustdoc-args` was never sent to rustc when building the build script.

**Comment by dtolnay** [comment]
@QuietMisdreavus figured it out in https://github.com/alexcrichton/proc-macro2/issues/145#issuecomment-437700181 -- this was a missing `rustc-args` on our end exposed by the upgrade from rustc 1.28.0-dev (b9bf4f162 2018-06-02) to rustc 1.31.0-nightly (78ff609d7 2018-10-19). Sorry for the false alarm!
