### ISSUE TITLE
Set default target for certain crates, also features

### ISSUE THREAD

**Issue by retep998** [rust-lang-nursery/docs.rs#29]
For certain crates I'd like it if I could set the default target, so that when someone looks up a certain crate, they'd get the documentation I want them to get by default. Particularly useful for crates that only define things for certain targets, such as `winapi`.

Also useful would be a way to tell docs.rs which features to enable when building a crate. `winapi` 0.3 will have almost everything disabled by default, and then opting in with features, but that would end up with docs.rs generating useless documentation.

**Comment by Yamakaky** [comment]
Same idea, but different problem: https://docs.rs/crate/clang-sys fails to find libclang (obviously). There is a feature to do a runtime link instead of a compile time link, so it should fix the problem.

**Comment by onur** [comment]
I will add building crates with extra features but where is best place to define docs.rs specific options?

Maybe a `docs.rs` section in `Cargo.toml`?

**Comment by steveklabnik** [comment]
IIRC, we made a `meta` section of Cargo.toml for this kind of thing

**Comment by steveklabnik** [comment]
Oh, it's `metadata` http://doc.crates.io/manifest.html#the-metadata-table-optional

**Comment by frewsxcv** [comment]
A use-case I have: [cocoa-rs](https://github.com/servo/cocoa-rs) is a crate managed by Servo. Servo currently does not build documentation on the OSX builders (https://doc.servo.org is Linux IIRC). It'd be nice if I could link to the documentation for cocoa-rs for the latest published version *that was built on OSX*. That said, I juts checked it looks like [cocoa-rs](https://docs.rs/crate/cocoa/0.5.0) isn't building on docs.rs, which makes my whole comment moot anyways.

**Comment by bluss** [comment]
Doc features are great. What I do in ndarray is to build with the "docs" feature that depends on the optional crate features. Then I've made sure each of the items enabled by that mentions this in the docs [(“*Requires crate feature "serde"*”)](https://bluss.github.io/rust-ndarray/master/ndarray/struct.ArrayBase.html#method.serialize). Adding this to docs.rs would make it have "feature parity" and I'll switch.

**Comment by onur** [comment]
This is partially fixed, looks like a commit closed this.

Docs.rs now supports building non-default features but it is not redirecting to default-target.

**Comment by retep998** [comment]
Would be *really* cool to have the default-target redirect working. It's incredibly frustrating when people look for the documentation for `winapi` only to find empty documentation.

**Comment by est31** [comment]
#255 fixed this

**Comment by QuietMisdreavus** [comment]
Crates that set a `default-target` in their `[package.metadata.docs.rs]` will now run their "test build" for that target, and their default docs set will be run on that target. In addition, crates with a default-target already set have had their latest version rebuilt; for example https://docs.rs/winapi/ now contains the proper docs for `x86_64-pc-windows-msvc` without having to redirect to that target's page. (Note that the builds still all run on a Linux system, so if your crate is target-specific because of a system library, that will still need to be available on Debian for the docs to build!)
